name: workflow-test

on:
  workflow_dispatch:

jobs:
  do_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        shell: bash 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./myscript.sh
          ./myscript.sh
